import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Masthead from "../components/masthead";
import About from "../components/about";
import NewAbout from "../components/newAbout";
import Campaigns from "../components/campaigns";
import Skills from "../components/skills";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>O Ultimo Príncipe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Masthead />
      <NewAbout />
      <Campaigns />
      {/* <About /> */}
      <Skills />
    </div>
  );
};

export default Home;
